# Generated by Django 4.1.3 on 2022-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnr_number", models.CharField(max_length=200, unique=True)),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Arbitration Petition", "Arbitration Petition"),
                            ("Civil (Appeal) Petition", "Civil (Appeal) Petition"),
                            ("Contempt Petition (Civil)", "Contempt Petition (Civil)"),
                            (
                                "Contempt Petition (Criminal)",
                                "Contempt Petition (Criminal)",
                            ),
                            ("Criminal Appeal Petition", "Criminal Appeal Petition"),
                            ("Election Petition", "Election Petition"),
                            ("Original Suit", "Original Suit"),
                            (
                                "Petition for Special Leave to Appeal",
                                "Petition for Special Leave to Appeal",
                            ),
                            ("Transferred Case Petition", "Transferred Case Petition"),
                            ("Writ Petition", "Writ Petition"),
                            (
                                "ARBITRATION Original Petition",
                                "ARBITRATION Original Petition",
                            ),
                            ("APPEAL SUIT", "APPEAL SUIT"),
                            ("ANDHRA TENANCY APPEAL", "ANDHRA TENANCY APPEAL"),
                            ("ANDHRA TENANCY CASE", "ANDHRA TENANCY CASE"),
                            ("COPY APPLICATION", "COPY APPLICATION"),
                            ("CALENDAR CASE-AP TRANSCO", "CALENDAR CASE-AP TRANSCO"),
                            (
                                "CALENDAR CASE LAND GRABBING",
                                "CALENDAR CASE LAND GRABBING",
                            ),
                            (
                                "CIVIL MISCELLEANOUS APPEAL",
                                "CIVIL MISCELLEANOUS APPEAL",
                            ),
                            ("CRIME NUMBER", "CRIME NUMBER"),
                            ("CRIMINAL APPEAL", "CRIMINAL APPEAL"),
                            (
                                "CRIME APPEAL METROPOLITAN UNIT",
                                "CRIME APPEAL METROPOLITAN UNIT",
                            ),
                            ("CRIMINAL MP", "CRIMINAL MP"),
                            ("CRLMP BAIL", "CRLMP BAIL"),
                            (
                                "CRIMINAL REVISION PETITION",
                                "CRIMINAL REVISION PETITION",
                            ),
                            (
                                "CRML. REV PETITION METROPOLITA",
                                "CRML. REV PETITION METROPOLITA",
                            ),
                            ("DOMESTIC VIOLENCE CASE", "DOMESTIC VIOLENCE CASE"),
                            ("Estate Abolition ACT", "Estate Abolition ACT"),
                            ("APPEAL UNDER EAT ACT", "APPEAL UNDER EAT ACT"),
                            ("EC ACT APPEALS", "EC ACT APPEALS"),
                            ("ECECTION OP", "ECECTION OP"),
                            ("ELECTRICITY MATER CASE", "ELECTRICITY MATER CASE"),
                            ("EXCEUTION PETITION", "EXCEUTION PETITION"),
                            ("ELECTRICITY SESSIONS CASE", "ELECTRICITY SESSIONS CASE"),
                            ("EMPLOYEES STATE INSURANCE", "EMPLOYEES STATE INSURANCE"),
                            ("FAMILY COURT OP", "FAMILY COURT OP"),
                            ("FAMILY COURT OS", "FAMILY COURT OS"),
                            ("GUARDIAN AND WARDS OP", "GUARDIAN AND WARDS OP"),
                            ("INDUSTRIAL DISPUTE", "INDUSTRIAL DISPUTE"),
                            ("INSOLVENCY PETITION", "INSOLVENCY PETITION"),
                            ("JUVENILE CALENDER CASE", "JUVENILE CALENDER CASE"),
                            ("LAND ACQUISITION OP", "LAND ACQUISITION OP"),
                            ("LAND GRABBING PETITION", "LAND GRABBING PETITION"),
                            ("LONG PENDING CASE", "LONG PENDING CASE"),
                            ("LAND REFORMS APPEAL", "LAND REFORMS APPEAL"),
                            ("LAND REFORMS APPEAL CASE", "LAND REFORMS APPEAL CASE"),
                            ("MAINTENANCE CASE", "MAINTENANCE CASE"),
                            ("MISC. PETITION IN ID", "MISC. PETITION IN ID"),
                            ("MOTOR ACCIDENT OP", "MOTOR ACCIDENT OP"),
                            ("ORIGINAL PETITION", "ORIGINAL PETITION"),
                            ("ORIGINAL SUIT", "ORIGINAL SUIT"),
                            ("PRE LITIGATION CASES", "PRE LITIGATION CASES"),
                            ("PRIMARY REGISTERED CASE", "PRIMARY REGISTERED CASE"),
                            ("REF. CHARGESHEET", "REF. CHARGESHEET"),
                            ("RENT APPEAL", "RENT APPEAL"),
                            ("RENT CONTROL CASE", "RENT CONTROL CASE"),
                            ("SESSION CASE", "SESSION CASE"),
                            ("SMALL CAUSE CASE", "SMALL CAUSE CASE"),
                            ("SESSION CASE UNDER IE ACT", "SESSION CASE UNDER IE ACT"),
                            (
                                "SESSION CASE-METROPOLITAN UNIT",
                                "SESSION CASE-METROPOLITAN UNIT",
                            ),
                            ("SESSIONS CASE-NDPS", "SESSIONS CASE-NDPS"),
                            (
                                "Protection of Children from Sexual Offences Act",
                                "Protection of Children from Sexual Offences Act",
                            ),
                            ("SESSIONS CASE-SC/ST", "SESSIONS CASE-SC/ST"),
                            ("SUCCESSION OP", "SUCCESSION OP"),
                            ("SUMMARY TRIAL CASE", "SUMMARY TRIAL CASE"),
                            ("TRCRLMP", "TRCRLMP"),
                            ("TRANSFER OP", "TRANSFER OP"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "filing_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("filing_date", models.DateField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("first_hearing_date", models.DateField(blank=True, null=True)),
                ("next_hearing_date", models.DateField(blank=True, null=True)),
                (
                    "stage_of_case",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coram", models.CharField(blank=True, max_length=500, null=True)),
                ("bench", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("judicial", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "causelist_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("under_act", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "under_section",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fir_state", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "fir_district",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fir_police_station",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fir_number", models.CharField(blank=True, max_length=50, null=True)),
                ("fir_year", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Labour Matters", "Labour Matters"),
                            ("Rent Act Matters", "Rent Act Matters"),
                            ("Direct Taxes Matter", "Direct Taxes Matter"),
                            ("Indirect Taxes Matters", "Indirect Taxes Matters"),
                            ("Indirect Taxes Matters", "Indirect Taxes Matters"),
                            ("Service Matters", "Service Matters"),
                            ("Academic Matters", "Academic Matters"),
                            (
                                "Letter Petition & Pil Matters",
                                "Letter Petition & Pil Matters",
                            ),
                            ("Election Matters", "Election Matters"),
                            (
                                "Company Law, Mrtp, Trai, Sebi, Idrai & Rbi",
                                "Company Law, Mrtp, Trai, Sebi, Idrai & Rbi",
                            ),
                            ("Arbitration Matters", "Arbitration Matters"),
                            ("Compensation Matters", "Compensation Matters"),
                            ("Habeas Corpus Matters", "Habeas Corpus Matters"),
                            ("Criminal Matters", "Criminal Matters"),
                            (
                                "Appeal Against Orders Of Statutory Bodies",
                                "Appeal Against Orders Of Statutory Bodies",
                            ),
                            ("Family Law Matters", "Family Law Matters"),
                            ("Contempt Of Court Matters", "Contempt Of Court Matters"),
                            ("Ordinary Civil Matters", "Ordinary Civil Matters"),
                            ("Three Judges Bench Matter", "Three Judges Bench Matter"),
                            ("Five Judges Bench Matter", "Five Judges Bench Matter"),
                            (
                                "Eleven Judges Bench Matter",
                                "Eleven Judges Bench Matter",
                            ),
                            ("Seven Judges Bench Matter", "Seven Judges Bench Matter"),
                            ("Nine Judges Bench Matter", "Nine Judges Bench Matter"),
                            (
                                "Appointments Etc., Of Constitutional Functionaries",
                                "Appointments Etc., Of Constitutional Functionaries",
                            ),
                            ("Personal Law Matters", "Personal Law Matters"),
                            (
                                "Religious & Charitable Endowments",
                                "Religious & Charitable Endowments",
                            ),
                            (
                                "Mercantile Laws, Commercial Transactions Including Banking",
                                "Mercantile Laws, Commercial Transactions Including Banking",
                            ),
                            (
                                "Simple Money & Mortgage Matters Etc",
                                "Simple Money & Mortgage Matters Etc",
                            ),
                            (
                                "Matters Relating To Judiciary",
                                "Matters Relating To Judiciary",
                            ),
                            (
                                "Admission To Educational Institutions Other Than Medical & Engineering",
                                "Admission To Educational Institutions Other Than Medical & Engineering",
                            ),
                            (
                                "Establishment And Recognition Of Educational Institutions",
                                "Establishment And Recognition Of Educational Institutions",
                            ),
                            (
                                "Eviction Under The Public Premises (Eviction) Act",
                                "Eviction Under The Public Premises (Eviction) Act",
                            ),
                            (
                                "Land Laws And Agricultural Tenancies",
                                "Land Laws And Agricultural Tenancies",
                            ),
                            (
                                "Admirality And Maritime Laws",
                                "Admirality And Maritime Laws",
                            ),
                            (
                                "Matters Relating To Consumer Protection",
                                "Matters Relating To Consumer Protection",
                            ),
                            (
                                "Matters Relating To Commissions Of Enquiry",
                                "Matters Relating To Commissions Of Enquiry",
                            ),
                            (
                                "Matters Pertaining To Armed Forces & Paramilitary Forces",
                                "Matters Pertaining To Armed Forces & Paramilitary Forces",
                            ),
                            (
                                "Admission/Transfer To Engineering And Medical Colleges",
                                "Admission/Transfer To Engineering And Medical Colleges",
                            ),
                            (
                                "ALLOCATION OF 15% ALL INDIA QUOTA IN ADMISSION/TRANSFER TO MEDICAL COLLEGES",
                                "ALLOCATION OF 15% ALL INDIA QUOTA IN ADMISSION/TRANSFER TO MEDICAL COLLEGES",
                            ),
                            (
                                "MATTERS RELATING TO LEASES, GOVT. CONTRACTS & CONTRACTS BY LOCAL BODIES",
                                "MATTERS RELATING TO LEASES, GOVT. CONTRACTS & CONTRACTS BY LOCAL BODIES",
                            ),
                            (
                                "State Excise-Trading In Liquor-Privileges, Licences-distilleries Breweries",
                                "State Excise-Trading In Liquor-Privileges, Licences-distilleries Breweries",
                            ),
                            (
                                "Reference Under Article 143 Of The Constitution Of India",
                                "Reference Under Article 143 Of The Constitution Of India",
                            ),
                            (
                                "Reference Under Article 317(1) Of The Constitution Of India",
                                "Reference Under Article 317(1) Of The Constitution Of India",
                            ),
                            (
                                "Refernce Under Section 11 Of The Competition Act, 2002",
                                "Refernce Under Section 11 Of The Competition Act, 2002",
                            ),
                            (
                                "Reference Under Section 14 Of The Right To Information Act, 2005",
                                "Reference Under Section 14 Of The Right To Information Act, 2005",
                            ),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_recieving", models.DateField(blank=True, null=True)),
                ("filed_by", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="document-details/"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cause_list_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("judge", models.CharField(blank=True, max_length=500, null=True)),
                ("business_on_date", models.DateField(blank=True, null=True)),
                ("hearing_date", models.DateField(blank=True, null=True)),
                (
                    "purpose_of_hearing",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrutiny_date", models.DateField(blank=True, null=True)),
                ("objection", models.CharField(blank=True, max_length=500, null=True)),
                ("compliance_date", models.DateField(blank=True, null=True)),
                ("reciept_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judge", models.CharField(blank=True, max_length=500, null=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "order_details",
                    models.FileField(blank=True, null=True, upload_to="order-details/"),
                ),
            ],
        ),
    ]
