# Generated by Django 4.1.3 on 2022-11-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("case", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdetails",
            name="advocate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="document",
            field=models.ManyToManyField(
                related_name="case_document", to="case.documentdetails"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="history",
            field=models.ManyToManyField(
                related_name="case_history", to="case.history"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="objection",
            field=models.ManyToManyField(
                related_name="case_objection", to="case.objection"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="order",
            field=models.ManyToManyField(related_name="case_order", to="case.order"),
        ),
        migrations.AddField(
            model_name="case",
            name="petitioner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_petitioner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="petitioner_advocate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="petitioner_advocate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_respondent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="respondent_advocate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="respondent_advocate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
