# Generated by Django 4.1.3 on 2022-11-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="case", name="document",),
        migrations.RemoveField(model_name="case", name="history",),
        migrations.RemoveField(model_name="case", name="objection",),
        migrations.RemoveField(model_name="case", name="order",),
        migrations.AddField(
            model_name="case",
            name="person_involved",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="person_involved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentdetails",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_document",
                to="case.case",
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_history",
                to="case.case",
            ),
        ),
        migrations.AddField(
            model_name="objection",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_objection",
                to="case.case",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_order",
                to="case.case",
            ),
        ),
        migrations.RemoveField(model_name="case", name="petitioner",),
        migrations.RemoveField(model_name="case", name="respondent",),
        migrations.AddField(
            model_name="case",
            name="petitioner",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="case_petitioner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="respondent",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="case_respondent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
